### PR TITLE
Italian and turkish

### PR DESCRIPTION
**Pull request by red1**
More Languages : Italian and turkish

### CODE REVIEW

**Comment by jelen07** [comment]
Hi @red1 ,

Is it a translation by a native speaker or some translator tool like Google, Deepl, etc.?

**Comment by numito** [comment]
I have checked the Italian translation and it is correct

**Comment by red1** [comment]
Sorry I missed this
 Yes I do speak Arabic as well. But didn't had the time to translate it

**Comment by gotanasro3** [comment]
[HR.json](https://github.com/68publishers/cookie-consent/files/14400208/HR.json)
[UA.json](https://github.com/68publishers/cookie-consent/files/14400209/UA.json)
[IT.json](https://github.com/68publishers/cookie-consent/files/14400214/IT.json)
[BG.json](https://github.com/68publishers/cookie-consent/files/14400217/BG.json)
[SE.json](https://github.com/68publishers/cookie-consent/files/14400219/SE.json)
[NO.json](https://github.com/68publishers/cookie-consent/files/14400220/NO.json)


Hi, I'm sending translations. Please, can you implement it in your extension so that I don't have to manually translate all translations via GTM?

**Comment by tg666** [comment]
@gotanasro3  Hi, thanks, I'll check it out tonight.
Are these translations made by native speakers, or were they translated using a translator/AI (Google, DeepL)?

Also, the translations for `BG` are already in the repository. Are yours more accurate?

**Comment by gotanasro3** [comment]
@tg666  All texts were translated by translators (people) according to the SK original.
BG translated extra. I didn't compare it.

**Comment by tg666** [comment]
@gotanasro3 New translations are released in the version `0.5.1`.
However, I changed the codes for Ukrainian (`ua` => `uk`) and Swedish (`se` => `sv`) because the codes follow the ISO 639-1 standard

**Pull request closed without merging**
